# Generated by Django 4.2.7 on 2023-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Gasto', models.CharField(max_length=3)),
                ('Fecha_financia', models.DateField()),
                ('ID_campana', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Promociona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Campana', models.CharField(max_length=9)),
                ('ID_Articulo', models.CharField(max_length=9)),
                ('Temporada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('DNI_Socio', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono_socio', models.CharField(max_length=9)),
                ('Correo', models.CharField(max_length=50)),
                ('N_tarjeta', models.CharField(max_length=16)),
                ('Domicilio', models.CharField(max_length=50)),
            ],
        ),
    ]
