# Generated by Django 4.2.7 on 2023-12-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanas',
            fields=[
                ('ID_Campana', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nom_Campana', models.CharField(max_length=50)),
                ('Tipo', models.CharField(max_length=50)),
                ('Duracion', models.IntegerField()),
                ('Presupuesto', models.IntegerField()),
            ],
        ),
    ]
