# Generated by Django 4.2.7 on 2023-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0002_campanas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('ID_gasto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Tipo_gasto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso_factura',
            fields=[
                ('ID_ingreso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Tipo_gasto', models.CharField(max_length=20)),
                ('DNI_Socio', models.CharField(max_length=9)),
                ('ID_Articulo', models.CharField(max_length=5)),
                ('Fecha_factura', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supone',
            fields=[
                ('ID_gasto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Nompro', models.CharField(max_length=30)),
                ('Deporte_especializado', models.CharField(max_length=50)),
                ('Fecha_pago', models.DateField()),
            ],
        ),
    ]
