# Generated by Django 4.2.7 on 2023-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0003_gastos_ingreso_factura_supone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('ID_Articulo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField()),
                ('Precio', models.IntegerField()),
                ('Deporte', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('DNI_Socio', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('ID_Articulo', models.CharField(max_length=5)),
                ('Fecha_factura', models.DateField()),
                ('Cantidad_compra', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Nompro', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, verbose_name='Nompro')),
                ('Deporte_especializado', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Telefono_proveedor', models.CharField(max_length=9)),
            ],
        ),
    ]
