# Generated by Django 4.2.7 on 2023-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplication', '0005_alter_proveedor_nompro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('DNI_Trabajador', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre_Trabajador', models.CharField(max_length=50)),
                ('Telefono_trabajador', models.CharField(max_length=9)),
                ('Salario', models.CharField(max_length=16)),
                ('Domicilio', models.CharField(max_length=50)),
            ],
        ),
    ]
